version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mynet
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - mynet
    depends_on: 
      - elasticsearch
  logstash:
    image: logstash_local
    container_name: logstash
    ports:
      - 5044:5044
    networks:
      - mynet
  tomcat:
    image: tomcat_local
    container_name: tomcat
    networks:
      - mynet
    ports:
      - "8080:8080"
networks:
  mynet:
    external: yes  
