version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mynet
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - mynet
    depends_on: 
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.1
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5400:5400"
    networks:
      - mynet
  tomcat:
    image: tomcat
    hostname: tomcat
    container_name: tomcat
    networks:
      - mynet
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    networks:
      - mynet
    ports:
      - "80:80"
networks:
  mynet:
    external: yes  
